routes/web.php
<?php
// manajemen job
Route::resource('todos', 'JobController');
Route::post('todos/search', 'JobController@search')->name('todos.search');
Route::get('todos/ambil/{id}', 'JobController@ambil')->name('todos.ambil');
Route::get('mytodo/{id}','JobController@show')->name('todos.mytodo');
Route::get('mytodo/{id_user}/edit/{id_job}','JobController@editMytodo')->name('todos.mytodo.edit');
Route::put('mytodo/{id_job}','JobController@updateMytodo')->name('todos.mytodo.update');
Route::get('done/{id}','JobController@done')->name('todos.done');

//manajemen project
Route::resource('projects', 'ProjectController');
Route::get('projects/todos/{id_project}','JobController@showByProject')->name('byProject.show');
Route::get('projects/todos/create/{id_project}','JobController@createByProject')->name('byProject.create');
Route::post('projects/todos/store/{id_project}', 'JobController@storeByProject')->name('byProject.store');
Route::get('projects/todos/{id_job}/edit', 'JobController@editByProject')->name('byProject.edit');
Route::put('projects/todos/{id_job}', 'JobController@updateByProject')->name('byProject.update');
Route::delete('projects/todos/{id_job}', 'JobController@destroyByProject')->name('byProject.destroy');

//manajemen user
Route::resource('programmers', 'UserController');
Route::get('programmers/todos/{id_user}','JobController@showByUser')->name('byUser.show');
Route::get('programmers/todos/create/{id_user}','JobController@createByUser')->name('byUser.create');
Route::post('programmers/todos/store/{id_user}', 'JobController@storeByUser')->name('byUser.store');
Route::get('programmers/todos/{id_job}/edit', 'JobController@editByUser')->name('byUser.edit');
Route::put('programmers/todos/{id_job}', 'JobController@updateByUser')->name('byUser.update');
Route::delete('programmers/todos/{id_job}', 'JobController@destroyByUser')->name('byUser.destroy');

Route::get('programmers/reset/{id}','UserController@reset')->name('programmers.reset');
Route::get('changePassword','UserController@editPassword')->name('user.editPass');
Route::post('changePassword','UserController@updatePassword')->name('user.updatePass');
Route::get('profil','UserController@editProfile')->name('profil.edit');
Route::put('profil','UserController@updateProfile')->name('profil.update');

Auth::routes();
Route::get('home', 'JobController@index')->name('home');
Route::get('/', function(){
	return redirect('/home');
});
Route::get('register', function(){
	return redirect('/');
});

Route::get('/datePicker', function(){
    return view('datepicker');
});

resources/views/pm/todo/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-8">
            <div class="card" style="padding-bottom:5px;">
                <div class="card-header"> Edit To Do </div>
                <div class="card-body" style="border-top:2px solid #eee; padding-top:20px;">
                    <form class="form-horizontal" action=" {{ route('todos.update', $job->id) }} " method="POST">
                        {{ csrf_field() }}
                        @method('PUT')
                        <div class="form-group">
                            <label for="project" class="col-md-4 control-label">Project</label>

                            <div class="col-md-6">
                                <select class="form-control" name="project" required>
                                    @foreach($projects as $project)
                                    <option value="{{$project->id}}"
                                        {{$project->id == $job->project_id ? 'selected' : '' }}>
                                        {{$project->name}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="programmer" class="col-md-4 control-label">Programmer</label>
                            <div class="col-md-6">
                                <select class="form-control" name="programmer">
                                    <option value="0">NOT SELECTED</option>
                                    @forelse($programmers as $programmer)
                                    <option value="{{$programmer->id}}"
                                        {{$programmer->id==auth()->user()->id?'selected':''}}>
                                        {{$programmer->name}}
                                    </option>
                                    @empty

                                    @endforelse
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="new-todo" class="col-md-4 control-label">Todo</label>
                            <div class="col-md-6">
                                <input id="new-todo" type="text" class="form-control" name="todo" value="{{$job->name}}" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="dateline" class="col-md-4 control-label">Deadline</label>
                            <div class="col-md-6">
                                <div class='input-group date' id='datePicker'>
                                    <input type='text' class="form-control" name="dateline" required/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('script')
<script type="text/javascript">
    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

    // var tanggal = new Date({!! json_encode($job->dateline, JSON_HEX_TAG) !!});

    // if(tanggal < today){
    //     today = tanggal;
    // }

    var optComponent = {
        startDate: today,
        format: 'dd/mm/yyyy',
        container: '#datePicker',
        orientation: 'auto top',
        todayHighlight: true,
        autoclose: true
    };

    // COMPONENT
    $( '#datePicker' ).datepicker( optComponent );
    $( '#datePicker' ).datepicker( 'setDate', '{{ $job->dateline }}' );
</script>
@endpush

resources/views/pm/todo/index.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="row" style="margin-bottom:20px;">
    <div class="col-md-7">
        <form class="form-inline" action=" {{ route('todos.search') }} " method="POST">
            @csrf
            <div class="form-group">
                <input class="form-control form-control-sm mr-3 w-75" type="text"
                placeholder="User/Project/Todo" aria-label="Search" name="search">
            </div>

            <div class="form-group">
                <div class='input-group date' id='datePicker'>
                    <input type='text' class="form-control" name="dateline" placeholder="Dateline"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

            <div class="form-group">
                    <button class="btn btn-primary" type="submit"> {{ __('Search') }} </button>

            </div>
        </form>
    </div>
    <div class="col-md-3">

    </div>
    <div class="col-md-2">
        <a class="btn btn-app-blue" href=" {{ route('todos.create') }} ">Add To Do</a>
    </div>
</div>

<table class="table">
    <thead class="thead-light">
        <tr>
            <th class="text-center" style="border-top:2px solid #eee;">No</th>
            <th class="text-center" style="border-top:2px solid #eee;">Project</th>
            <th class="text-center" style="border-top:2px solid #eee;">To Do</th>
            <th class="text-center" style="border-top:2px solid #eee;">Programmer</th>
            <th class="text-center" style="border-top:2px solid #eee;">Progress</th>
            <th class="text-center" style="border-top:2px solid #eee;">Posted</th>
            <th class="text-center" style="border-top:2px solid #eee;">Deadline</th>
            <th class="text-center" style="border-top:2px solid #eee;">Aksi</th>
        </tr>
    </thead>
    <tbody>
        @forelse($jobs as $job)
        <tr>
            <td class="text-center">{{$loop->iteration}}</td>
            <td class="text-center">{{$job->project->name}}</td>
            <td class="text-center">{{$job->name}}</td>
            @if($job->user_id==0)
            <td class="text-center">Belum Ada</td>
            @else
            <td class="text-center">{{$job->user->name}}</td>
            @endif

            <td class="text-center"> {{ $job->status }} </td>
            <td class="text-center">{{ $job->created_at->format('d/m/Y') }}</td>
            <td class="text-center">{{ $job->dateline }}</td>
            <td class="text-center" style="display: flex;justify-content:center">
                <table>
                    <tr>
                        <td>
                            <a href="{{ route('todos.edit', $job->id) }}" class="btn btn-sm btn-success" title="Edit">
                                Edit
                            </a>
                        </td>
                        <td>
                            <form id="delete-form" action="{{ route('todos.destroy',$job->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                        <td>
                            <a href="{{ route('todos.ambil', $job->id) }}" class="btn btn-sm btn-primary" title="Ambil">
                                Ambil
                            </a>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="12">
                <div class="alert alert-warning text-center mb0">
                    <p>Data Not Found</p>
                </div>
            </td>
        </tr>
        @endforelse
    </tbody>
</table>
<div style="display: flex;justify-content:center;">
    {{ $jobs->links() }}
</div>
@endsection
@push('script')
<script type="text/javascript">
    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

    var optComponent = {
        format: 'dd/mm/yyyy',
        container: '#datePicker',
        orientation: 'auto bottom',
        todayHighlight: true,
        autoclose: true
    };

    // COMPONENT
    $('#datePicker').datepicker(optComponent);
</script>
@endpush

resources/views/pm/todo/tambah.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-8">
            <div class="card" style="padding-bottom:5px;">
                <div class="card-header">Tambah To Do</div>
                <div class="card-body" style="border-top:2px solid #eee; padding-top:20px;">
                    <form class="form-horizontal" method="POST" action=" {{ route('todos.store') }} ">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="project" class="col-md-4 control-label">Project</label>

                            <div class="col-md-6">
                                <select class="form-control" name="project" required>
                                    <option value="">SELECT PROJECT</option>
                                    @forelse($projects as $project)
                                    <option value={{$project->id}}>{{$project->name}}</option>
                                    @empty
                                    <option>No Project</option>
                                    @endforelse
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="programmer" class="col-md-4 control-label">Programmer</label>

                            <div class="col-md-6">
                                <select class="form-control" name="programmer">
                                    <option value="0">NOT SELECTED</option>
                                    @forelse($programmers as $programmer)
                                    <option value="{{$programmer->id}}">
                                        {{$programmer->name}}
                                    </option>
                                    @empty

                                    @endforelse
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="new-todo" class="col-md-4 control-label">Todo</label>
                            <div class="col-md-6">
                                <input id="new-todo" type="text" class="form-control" name="todo" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="dateline" class="col-md-4 control-label">Deadline</label>
                            <div class="col-md-6">
                                <div class='input-group date' id='datePicker'>
                                    <input type='text' class="form-control" name="dateline" required/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Tambah
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')
<script type="text/javascript">
    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

    var optComponent = {
        startDate: today,
        format: 'dd/mm/yyyy',
        container: '#datePicker',
        orientation: 'auto top',
        todayHighlight: true,
        autoclose: true
    };

    // COMPONENT
    $( '#datePicker' ).datepicker( optComponent );

    $( '#datePicker' ).datepicker( 'setDate', today );
</script>
@endpush