routes/web.php
<?php
// manajemen job
Route::resource('todos', 'JobController');
Route::post('todos/search', 'JobController@search')->name('todos.search');
Route::get('todos/ambil/{id}', 'JobController@ambil')->name('todos.ambil');
Route::get('mytodo/{id}','JobController@show')->name('todos.mytodo');
Route::get('mytodo/{id_user}/edit/{id_job}','JobController@editMytodo')->name('todos.mytodo.edit');
Route::put('mytodo/{id_job}','JobController@updateMytodo')->name('todos.mytodo.update');
Route::get('done/{id}','JobController@done')->name('todos.done');

//manajemen project
Route::resource('projects', 'ProjectController');
Route::get('projects/todos/{id_project}','JobController@showByProject')->name('byProject.show');
Route::get('projects/todos/create/{id_project}','JobController@createByProject')->name('byProject.create');
Route::post('projects/todos/store/{id_project}', 'JobController@storeByProject')->name('byProject.store');
Route::get('projects/todos/{id_job}/edit', 'JobController@editByProject')->name('byProject.edit');
Route::put('projects/todos/{id_job}', 'JobController@updateByProject')->name('byProject.update');
Route::delete('projects/todos/{id_job}', 'JobController@destroyByProject')->name('byProject.destroy');

//manajemen user
Route::resource('programmers', 'UserController');
Route::get('programmers/todos/{id_user}','JobController@showByUser')->name('byUser.show');
Route::get('programmers/todos/create/{id_user}','JobController@createByUser')->name('byUser.create');
Route::post('programmers/todos/store/{id_user}', 'JobController@storeByUser')->name('byUser.store');
Route::get('programmers/todos/{id_job}/edit', 'JobController@editByUser')->name('byUser.edit');
Route::put('programmers/todos/{id_job}', 'JobController@updateByUser')->name('byUser.update');
Route::delete('programmers/todos/{id_job}', 'JobController@destroyByUser')->name('byUser.destroy');

Route::get('programmers/reset/{id}','UserController@reset')->name('programmers.reset');
Route::get('changePassword','UserController@editPassword')->name('user.editPass');
Route::post('changePassword','UserController@updatePassword')->name('user.updatePass');
Route::get('profil','UserController@editProfile')->name('profil.edit');
Route::put('profil','UserController@updateProfile')->name('profil.update');

Auth::routes();
Route::get('home', 'JobController@index')->name('home');
Route::get('/', function(){
	return redirect('/home');
});
Route::get('register', function(){
	return redirect('/');
});

Route::get('/datePicker', function(){
    return view('datepicker');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'role', 'photo'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function job()
    {
        return $this->hasMany(Job::class);
    }

    public function project()
    {
        return $this->hasMany(Project::class);
    }

    public function isAdmin()
    {
        return $this->role == 1;
    }

    public function isProgrammer()
    {
        return $this->role == 0;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Auth;
use App\User;
use App\Job;
use Illuminate\Support\Facades\Storage;
use File;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin',['except' => ['editPassword','updatePassword','editProfile','updateProfile','show']]);
    }

    public function index()
    {
        $programmers = User::orderBy('role','DESC')->paginate(5);
        return view('pm.user.index', compact('programmers'));
    }

    public function create()
    {
        return view('pm.user.tambah');
    }

    public function store(Request $request)
    {
        $programmer = new User([
            'name' => $request->programmer,
            'email' =>$request->email,
            'password' => Hash::make($request->password),
            'role' => $request->role,
            'photo' => 'profile/default.jpg',
        ]);
        $programmer->save();

        return redirect()->route('programmers.index');
    }

    public function show($id)
    {
        $user = User::find(auth()->user()->id);
        return view('profile.index',compact('user'));
    }

    public function edit($id)
    {
        $programmer = User::find($id);
        return view('pm.user.edit', compact('programmer'));
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request->programmer;
        $user->role = $request->role;
        $user->save();

        return redirect()->route('programmers.index');
    }

    public function destroy($id)
    {
        User::find($id)->delete();
        Job::where('user_id','=',$id)->update(['user_id' => 0]);
        return redirect()->route('programmers.index');
    }

    public function editPassword(){
        return view('auth.changepassword');
    }

    public function updatePassword(Request $request){
        if (!(Hash::check($request->get('current-password'), Auth::user()->password))) {
            // The passwords matches
            return redirect()->back()->with("error","Your current password does not matches with the password you provided. Please try again.");
        }
        if(strcmp($request->get('current-password'), $request->get('new-password')) == 0){
            //Current password and new password are same
            return redirect()->back()->with("error","New Password cannot be same as your current password. Please choose a different password.");
        }
        $request->validate([
            'current-password' => 'required',
            'new-password' => 'required|string|min:6|confirmed',
        ]);
        //Change Password
        $user = Auth::user();
        $user->password = bcrypt($request->get('new-password'));
        $user->save();
        return redirect()->back()->with("success","Password changed successfully !");
    }

    public function editProfile(){
        $user = User::find(auth()->user()->id);
        return view('profile.index',compact('user'));
    }

    public function updateProfile(Request $request){
        $request->validate([
            'image' => 'mimes:jpeg,jpg,png',
        ]);

        if($request->image != null){
            $path = $request->file('image')->store('profile');
        }else{
            $path = User::find(auth()->user()->id)->photo;
        }

        User::where('id',auth()->user()->id)->update([
            'photo' => $path,
            'name'  => $request->name,
            'email' => $request->email,
        ]);
        return redirect()->route('profil.edit');
    }

    public function reset($id){
        User::find($id)->update([
            'password' => bcrypt('123456'),
        ]);

        return redirect()->route('programmers.index');
    }
}

resources/views/pm/user/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-8">
            <div class="card" style="padding-bottom:5px;">
                <div class="card-header"> Edit Programmer </div>
                <div class="card-body" style="border-top:2px solid #eee; padding-top:20px;"S>
                    <form class="form-horizontal" action="{{ route('programmers.update',$programmer->id) }}" method="POST">
                        {{ csrf_field() }}
                        @method('PUT')
                        <div class="form-group">
                            <label for="programmer" class="col-md-4 control-label">Nama</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="programmer"
                                value="{{$programmer->name}}" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="col-md-4 control-label">Posisi</label>

                            <div class="col-md-6">
                                <select name="role" class="form-control">
                                    <option value="0" {{$programmer->role == 0 ? 'selected' : ''}}>
                                        Programmer
                                    </option>
                                    <option value="1" {{$programmer->role == 1 ? 'selected' : ''}}>
                                        Project Manager
                                    </option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pm/user/index.blade.php
<!DOCTYPE html>
@extends('layouts.dashboard')

@section('content')
<div class="row" style="margin-bottom:20px;">
    <div class="col-md-2">
        <a class="btn btn-app-blue" href=" {{ route('programmers.create') }} ">Add Programmer</a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th class="text-center" style="border-top:2px solid #eee;">No</th>
            <th class="text-center" style="border-top:2px solid #eee;">Nama</th>
            <th class="text-center" style="border-top:2px solid #eee;">Posisi</th>
            <th class="text-center" style="border-top:2px solid #eee;">Aksi</th>
        </tr>
    </thead>
    <tbody>
        @forelse($programmers as $programmer)
        <tr>
            <td class="text-center">{{$loop->iteration}}</td>
            <td class="text-center"><a href="{{ route('byUser.show',$programmer->id) }}">{{$programmer->name}}</a></td>
            <td class="text-center">
                @if($programmer->role==1)
                Project Manager
                @else
                Programmer
                @endif
            </td>
            <td class="text-center" style="display: flex;justify-content:center">
                <table>
                    <tr>
                        <td>
                            <a href=" {{ route('programmers.edit', $programmer->id) }} " class="btn btn-sm btn-success" title="Edit">
                                Edit
                            </a>
                        </td>
                        <td>
                            <form id="delete-form" action=" {{ route('programmers.destroy',$programmer->id) }} "
                                method="POST">
                                @csrf
                                @method("delete")
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                        <td>
                            <a href=" {{ route('programmers.reset', $programmer->id) }} " class="btn btn-sm btn-primary" title="Edit">
                                Reset
                            </a>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="6">
                <div class="alert alert-warning text-center mb0">
                    <p>Data Not Found</p>
                </div>
            </td>
        </tr>
        @endforelse
    </tbody>
</table>
<div style="display: flex;justify-content:center;">
    {{ $programmers->links() }}
</div>
@endsection

resources/views/pm/user/tambah.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-8">
            <div class="card" style="padding-bottom:5px;">
                <div class="card-header">Tambah Programmer</div>
                <div class="card-body" style="border-top:2px solid #eee; padding-top:20px;">
                    <form class="form-horizontal" method="POST" action=" {{ route('programmers.store') }} ">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="programmer" class="col-md-4 control-label">Nama</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="programmer" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control" name="password" value="12345678" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="col-md-4 control-label">Email</label>

                            <div class="col-md-6">
                                <input type="email" class="form-control" name="email" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="col-md-4 control-label">Posisi</label>

                            <div class="col-md-6">
                                <select name="role" class="form-control">
                                    <option value="0">Programmer</option>
                                    <option value="1">Project Manager</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Tambah
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection