routes/web.php
<?php
// manajemen job
Route::resource('todos', 'JobController');
Route::post('todos/search', 'JobController@search')->name('todos.search');
Route::get('todos/ambil/{id}', 'JobController@ambil')->name('todos.ambil');
Route::get('mytodo/{id}','JobController@show')->name('todos.mytodo');
Route::get('mytodo/{id_user}/edit/{id_job}','JobController@editMytodo')->name('todos.mytodo.edit');
Route::put('mytodo/{id_job}','JobController@updateMytodo')->name('todos.mytodo.update');
Route::get('done/{id}','JobController@done')->name('todos.done');

//manajemen project
Route::resource('projects', 'ProjectController');
Route::get('projects/todos/{id_project}','JobController@showByProject')->name('byProject.show');
Route::get('projects/todos/create/{id_project}','JobController@createByProject')->name('byProject.create');
Route::post('projects/todos/store/{id_project}', 'JobController@storeByProject')->name('byProject.store');
Route::get('projects/todos/{id_job}/edit', 'JobController@editByProject')->name('byProject.edit');
Route::put('projects/todos/{id_job}', 'JobController@updateByProject')->name('byProject.update');
Route::delete('projects/todos/{id_job}', 'JobController@destroyByProject')->name('byProject.destroy');

//manajemen user
Route::resource('programmers', 'UserController');
Route::get('programmers/todos/{id_user}','JobController@showByUser')->name('byUser.show');
Route::get('programmers/todos/create/{id_user}','JobController@createByUser')->name('byUser.create');
Route::post('programmers/todos/store/{id_user}', 'JobController@storeByUser')->name('byUser.store');
Route::get('programmers/todos/{id_job}/edit', 'JobController@editByUser')->name('byUser.edit');
Route::put('programmers/todos/{id_job}', 'JobController@updateByUser')->name('byUser.update');
Route::delete('programmers/todos/{id_job}', 'JobController@destroyByUser')->name('byUser.destroy');

Route::get('programmers/reset/{id}','UserController@reset')->name('programmers.reset');
Route::get('changePassword','UserController@editPassword')->name('user.editPass');
Route::post('changePassword','UserController@updatePassword')->name('user.updatePass');
Route::get('profil','UserController@editProfile')->name('profil.edit');
Route::put('profil','UserController@updateProfile')->name('profil.update');

Auth::routes();
Route::get('home', 'JobController@index')->name('home');
Route::get('/', function(){
	return redirect('/home');
});
Route::get('register', function(){
	return redirect('/');
});

Route::get('/datePicker', function(){
    return view('datepicker');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @stack('style')
</head>

<body>
    <div id="app">
        @guest

        @else
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
        @endguest
        <main class="">
            @guest

            @else
            <ul>
                @if(Auth::User()->isAdmin())
                <li><a href="/pm">Home</a></li>
                <li><a href="/project">Project</a></li>
                <li><a href="/manage">Manajemen User</a></li>
                @elseif(Auth::User()->role==0)
                <li><a href="/pro">Home</a></li>
                @endif
                <li><a href="/mytodo">My To Do</a></li>
                <li><a href="/changePassword">Ganti Password</a></li>
            </ul>
            @endguest
            @yield('content')
        </main>
    </div>
    @stack('script')
</body>

</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>

<html class="app-ui">

<head>
    <!-- Meta -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Document title -->
    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- Google fonts -->
    {{-- <link rel="stylesheet"
        href="http://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,900%7CRoboto+Slab:300,400%7CRoboto+Mono:400" /> --}}
    <!-- AppUI CSS stylesheets -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" id="css-ionicons" href="{{ asset('css/ionicons.css') }}" />
    <link rel="stylesheet" id="css-bootstrap" href="{{ asset('css/bootstrap.css') }}" />
    <link rel="stylesheet" id="css-app" href="{{ asset('css/app2.css') }}" />
    <!-- End Stylesheets -->
    <style>
        .btn.btn-rounded {
        border-radius: 50px;
    }
    </style>
    @stack('styles')
</head>

<body class="app-ui layout-has-drawer layout-has-fixed-header">
    <div class="app-layout-canvas">
        <div class="app-layout-container">
            <!-- Drawer -->
            <aside class="app-layout-drawer">
                <!-- Drawer scroll area -->
                <div class="app-layout-drawer-scroll">
                    <!-- Drawer logo -->
                    <div id="logo" class="drawer-header">
                        <a href="/home">
                            <img class="img-responsive" src="{{ asset('img/logo/geekgarden.png') }}"
                                title="GeekGarden" alt="GeekGarden" />
                            </a>
                    </div>
                    <!-- Drawer navigation -->
                    <nav class="drawer-main">
                        <ul class="nav nav-drawer">
                            <li class="nav-item {{ Request::is('todos*') ? 'active' : '' }}">
                                <a href=" {{ route('todos.index') }} "><i
                                        class="ion-ios-speedometer-outline"></i>Dashboard</a>
                            </li>
                            @if(Auth::User()->isAdmin())
                            <li class="nav-item {{ Request::is('projects*') ? 'active' : '' }}">
                                <a href=" {{ route('projects.index') }} "><i class="ion-ios-briefcase"></i>Project</a>
                            </li>
                            <li class="nav-item {{ Request::is('programmers*') ? 'active' : '' }}">
                                <a href=" {{ route('programmers.index') }} "><i class="ion-ios-people"></i>Manage
                                    User</a>
                            </li>
                            @endif
                            <li class="nav-item {{ Request::is('mytodo*') ? 'active' : '' }}">
                                <a href="/mytodo/{{auth()->user()->id}}"><i class="ion-ios-contact"></i>My To Do</a>
                            </li>
                            <li class="nav-item {{ Request::is('changePassword*') ? 'active' : '' }}">
                                <a href=" {{ route('user.editPass') }} "><i class="ion-ios-redo"></i>Change Password</a>
                            </li>
                        </ul>
                    </nav>
                    <!-- End drawer navigation -->
                    <div class="drawer-footer">
                        <p class="copyright">AppUI Template &copy;</p>
                        <a href="https://shapebootstrap.net/item/1525731-appui-admin-frontend-template/?ref=rustheme"
                            target="_blank" rel="nofollow">Purchase a license</a>
                    </div>
                </div>
                <!-- End drawer scroll area -->
            </aside>
            <!-- End drawer -->

            <!-- Header -->
            <header class="app-layout-header">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <a class="btn btn-sm btn-rounded btn-primary" id="btn-back" href="javascript:window.history.go(-1);">
                                <b>Back</b>
                            </a>
                            <span class="navbar-page-title">
                                {{ Auth::user()->role==1?'Project Manager':'Programmer'}}
                            </span>
                        </div>

                        <div class="collapse navbar-collapse" id="header-navbar-collapse">

                            <ul class="nav navbar-nav navbar-right navbar-toolbar hidden-sm hidden-xs">
                                <li class="dropdown dropdown-profile">
                                    <a href="javascript:void(0)" data-toggle="dropdown">
                                        <span class="m-r-sm">{{ Auth::user()->name }} <span class="caret"></span></span>
                                        <img class="img-avatar img-avatar-48" @if (auth()->user()->photo)
                                        src="{{ asset(auth()->user()->photo) }}"
                                        @else
                                        src="{{ asset('img/avatars/avatar3.jpg') }}"
                                        @endif
                                        alt="User profile"/>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>
                                            <a href=" {{ route('profil.edit') }} ">Profile</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                            </a>

                                            <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                                style="display: none;">
                                                @csrf
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <!-- .navbar-right -->
                        </div>
                    </div>
                    <!-- .container-fluid -->
                </nav>
                <!-- .navbar-default -->
            </header>
            <!-- End header -->

            <main class="app-layout-content">
                <!-- Page Content -->
                <div class="container-fluid p-y-md">
                    @yield('content')
                </div>
                <!-- End Page Content -->
            </main>
        </div>
        <!-- .app-layout-container -->
    </div>

    <!-- AppUI Core JS: jQuery, Bootstrap, slimScroll, scrollLock and App.js -->
    <script src="{{ asset('js/core/bootstrap.min.js') }}"></script>
    @stack('script')
</body>

</html>