routes/web.php
<?php
// manajemen job
Route::resource('todos', 'JobController');
Route::post('todos/search', 'JobController@search')->name('todos.search');
Route::get('todos/ambil/{id}', 'JobController@ambil')->name('todos.ambil');
Route::get('mytodo/{id}','JobController@show')->name('todos.mytodo');
Route::get('mytodo/{id_user}/edit/{id_job}','JobController@editMytodo')->name('todos.mytodo.edit');
Route::put('mytodo/{id_job}','JobController@updateMytodo')->name('todos.mytodo.update');
Route::get('done/{id}','JobController@done')->name('todos.done');

//manajemen project
Route::resource('projects', 'ProjectController');
Route::get('projects/todos/{id_project}','JobController@showByProject')->name('byProject.show');
Route::get('projects/todos/create/{id_project}','JobController@createByProject')->name('byProject.create');
Route::post('projects/todos/store/{id_project}', 'JobController@storeByProject')->name('byProject.store');
Route::get('projects/todos/{id_job}/edit', 'JobController@editByProject')->name('byProject.edit');
Route::put('projects/todos/{id_job}', 'JobController@updateByProject')->name('byProject.update');
Route::delete('projects/todos/{id_job}', 'JobController@destroyByProject')->name('byProject.destroy');

//manajemen user
Route::resource('programmers', 'UserController');
Route::get('programmers/todos/{id_user}','JobController@showByUser')->name('byUser.show');
Route::get('programmers/todos/create/{id_user}','JobController@createByUser')->name('byUser.create');
Route::post('programmers/todos/store/{id_user}', 'JobController@storeByUser')->name('byUser.store');
Route::get('programmers/todos/{id_job}/edit', 'JobController@editByUser')->name('byUser.edit');
Route::put('programmers/todos/{id_job}', 'JobController@updateByUser')->name('byUser.update');
Route::delete('programmers/todos/{id_job}', 'JobController@destroyByUser')->name('byUser.destroy');

Route::get('programmers/reset/{id}','UserController@reset')->name('programmers.reset');
Route::get('changePassword','UserController@editPassword')->name('user.editPass');
Route::post('changePassword','UserController@updatePassword')->name('user.updatePass');
Route::get('profil','UserController@editProfile')->name('profil.edit');
Route::put('profil','UserController@updateProfile')->name('profil.update');

Auth::routes();
Route::get('home', 'JobController@index')->name('home');
Route::get('/', function(){
	return redirect('/home');
});
Route::get('register', function(){
	return redirect('/');
});

Route::get('/datePicker', function(){
    return view('datepicker');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
	protected $fillable = [
        'name'
    ];

    public function user()
	{
	    return $this->belongsTo(User::class);
	}

	public function job()
    {
        return $this->hasMany(Job::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\Job;

class ProjectController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
    }

    public function index()
    {
        $projects = Project::orderBy('name')->paginate(5);
        return view('pm.project.index', compact('projects'));
    }

    public function create()
    {
        return view('pm.project.tambah');
    }

    public function store(Request $request)
    {
        $project = new Project([
            'name' => $request->project
        ]);
        $project->save();

        return redirect()->route('projects.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $project = Project::find($id);

        return view('pm.project.edit', compact('project'));
    }

    public function update(Request $request, $id)
    {
        $project = Project::find($id);
        $project->name = $request->project;
        $project->save();

        return redirect()->route('projects.index');
    }

    public function destroy($id)
    {
        Project::find($id)->delete();
        Job::where('project_id','=',$id)->delete();

        return redirect()->route('projects.index');
    }
}

resources/views/pm/project/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-8">
            <div class="card" style="padding-bottom:5px;">
                <div class="card-header"> Edit Project </div>
                <div class="card-body" style="border-top:2px solid #eee; padding-top:20px;"S>
                    <form class="form-horizontal" action="{{ route('projects.update',$project->id) }}" method="POST">
                        {{ csrf_field() }}
                        @method('PUT')
                        <div class="form-group">
                            <label for="project" class="col-md-4 control-label">Project</label>

                            <div class="col-md-6">
                                <input class="form-control" type="text" name="project" value="{{$project->name}}" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pm/project/index.blade.php
@extends('layouts.dashboard')

@push('styles')
<style>

</style>
@endpush
@section('content')
<div class="row" style="margin-bottom:20px;">
    <div class="col-md-2">
        <a class="btn btn-app-blue" href=" {{ route('projects.create') }} ">Add Project</a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th class="text-center" style="border-top:2px solid #eee;">No</th>
            <th class="text-center" style="border-top:2px solid #eee;">Project</th>
            <th class="text-center" style="border-top:2px solid #eee;">Aksi</th>
        </tr>
    </thead>
    <tbody>
        @forelse($projects as $project)
        <tr>
            <td class="text-center">{{$loop->iteration}}</td>
            <td class="text-center"><a href="{{ route('byProject.show',$project->id) }}">{{$project->name}}</a></td>
            <td class="text-center" style="display: flex;justify-content:center">
                <table>
                    <tr>
                        <td>
                            <a href=" {{ route('projects.edit',$project->id) }} " class="btn btn-sm btn-success" title="Edit">
                                Edit
                            </a>
                        </td>
                        <td>
                            <form id="delete-form" action=" {{ route('projects.destroy',$project->id) }}" method="POST">
                                @csrf
                                @method("delete")
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="6">
                <div class="alert alert-warning text-center mb0">
                    <p>Data Not Found</p>
                </div>
            </td>
        </tr>
        @endforelse
    </tbody>
</table>
<div style="display: flex;justify-content:center;">
    {{ $projects->links() }}
</div>
@endsection

resources/views/pm/project/tambah.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container">
    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-8">
            <div class="card" style="padding-bottom:5px;">
                <div class="card-header">Tambah Project</div>
                <div class="card-body" style="border-top:2px solid #eee; padding-top:20px;">
                    <form class="form-horizontal" method="POST" action=" {{ route('projects.store') }} ">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="newproject" class="col-md-4 control-label">Project</label>

                            <div class="col-md-6">
                                <input type="text" class="form-control" name="project" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Tambah
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection